# Generated by Django 3.2.9 on 2021-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureManager', '0002_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Continent',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='location',
            name='continent',
            field=models.CharField(default='desc', max_length=40),
            preserve_default=False,
        ),
    ]
